== 행사

=== 행사 생성

operation::createEvent[snippets="http-request,request-body,request-fields,response-body,response-fields,http-response,response-cookies"]
==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
   {
      "code":"REQUEST_EMPTY",
      "message":"행사 이름은 공백일 수 없습니다."
   },
   {
      "code":"EVENT_NAME_LENGTH_INVALID",
      "message":"행사 이름은 2자 이상 30자 이하만 입력 가능합니다. 입력한 이름 길이 : 21"
   },
   {
      "code":"EVENT_NAME_MULTIPLE_BLANK",
      "message":"행사 이름에는 공백 문자가 연속될 수 없습니다. 입력한 이름 : 공백  문자"
   },
  {
      "code":"EVENT_PASSWORD_INVALID",
      "message":"비밀번호는 4자리 숫자만 가능합니다."
   }
]
----

=== 행사 관리자 로그인

operation::eventLogin[snippets="path-parameters,http-request,request-body,request-fields,http-response,response-cookies"]
==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
   {
      "code":"EVENT_NOT_FOUND",
      "message":"존재하지 않는 행사입니다."
   },
   {
      "code":"REQUEST_EMPTY",
      "message":"비밀번호는 공백일 수 없습니다."
   },
   {
      "code":"PASSWORD_INVALID",
      "message":"비밀번호가 일치하지 않습니다."
   }
]
----

=== 행사 정보 조회

operation::getEvent[snippets="path-parameters,http-request,response-body,response-fields,http-response"]

==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
   {
      "code":"EVENT_NOT_FOUND",
      "message":"존재하지 않는 행사입니다."
   }
]
----

=== 행사 전체 참여자 목록 조회

operation::findAllMembers[snippets="path-parameters,http-request,response-body,response-fields,http-response,response-fields"]

==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
   {
      "code":"EVENT_NOT_FOUND",
      "message":"존재하지 않는 행사입니다."
   }
]
----

=== 행사 전체 지출 이력 조회

operation::findBills[snippets="path-parameters,http-request,http-response,response-fields"]

==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
   {
      "code":"EVENT_NOT_FOUND",
      "message":"존재하지 않는 행사입니다."
   }
]
----

=== 행사 참여자 정보 변경

operation::updateMembers[snippets="path-parameters,http-request,request-body,request-fields,http-response,request-cookies"]
==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[

   {
      "code":"MEMBER_NAME_CHANGE_DUPLICATE",
      "message":"중복된 참여 인원 이름 변경 요청이 존재합니다."
   },
   {
      "code":"MEMBER_NOT_EXIST",
      "message":"현재 참여하고 있지 않는 인원이 존재합니다."
   },
   {
      "code":"REQUEST_EMPTY",
      "message":"멤버 이름은 공백일 수 없습니다."
   },
   {
      "code":"MEMBER_NAME_LENGTH_INVALID",
      "message":"멤버 이름은 1자 이상 4자 이하만 입력 가능합니다."
   },
   {
      "code":"EVENT_NOT_FOUND",
      "message":"존재하지 않는 행사입니다."
   },
   {
      "code":"MEMBER_NAME_DUPLICATE",
      "message":"중복된 행사 참여 인원 이름이 존재합니다."
   },
   {
      "code":"TOKEN_NOT_FOUND",
      "message":"토큰이 존재하지 않습니다."
   },
   {
      "code":"TOKEN_EXPIRED",
      "message":"만료된 토큰입니다."
   },
   {
      "code":"TOKEN_INVALID",
      "message":"유효하지 않은 토큰입니다."
   }
]
----

=== 행사 참여자 삭제

operation::deleteMember[snippets="path-parameters,http-request,http-response,request-cookies"]
==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
   {
      "code":"EVENT_NOT_FOUND",
      "message":"존재하지 않는 행사입니다."
   },
   {
      "code":"TOKEN_NOT_FOUND",
      "message":"토큰이 존재하지 않습니다."
   },
   {
      "code":"TOKEN_EXPIRED",
      "message":"토큰이 존재하지 않습니다."
   },
   {
      "code":"TOKEN_INVALID",
      "message":"유효하지 않은 토큰입니다."
   }
]
----

=== 행사 어드민 권한 확인

operation::authenticateEvent[snippets="http-request,http-response,request-cookies"]
==== [.red]#Exceptions#

[source,json,options="nowrap"]
----
[
   {
      "code": "EVENT_NOT_FOUND",
      "message": "존재하지 않는 행사입니다."
   },
   {
      "code": "TOKEN_NOT_FOUND",
      "message": "토큰이 존재하지 않습니다."
   },
   {
      "code": "TOKEN_EXPIRED",
      "message": "만료된 토큰입니다."
   },
   {
      "code": "TOKEN_INVALID",
      "message": "유효하지 않은 토큰입니다."
   },
   {
      "code": "FORBIDDEN",
      "message": "접근할 수 없는 행사입니다."
   }
]
----
