const BANKS = [
  {name: '우리은행', displayName: '우리은행', iconPosition: '-10px -10px'},
  {name: 'SC제일은행', displayName: '제일은행', iconPosition: '-110px -10px'},
  {name: '신한은행', displayName: '신한은행', iconPosition: '-10px -110px'},
  {name: 'KB국민은행', displayName: 'KB국민은행', iconPosition: '-110px -110px'},
  {name: '하나은행', displayName: '하나은행', iconPosition: '-210px -10px'},
  {name: '씨티은행', displayName: '씨티은행', iconPosition: '-210px -110px'},
  {name: 'IM뱅크', displayName: 'IM뱅크', iconPosition: '-10px -210px'},
  {name: '부산은행', displayName: '부산은행', iconPosition: '-110px -210px'},
  {name: '경남은행', displayName: '경남은행', iconPosition: '-210px -210px'},
  {name: '광주은행', displayName: '광주은행', iconPosition: '-310px -10px'},
  {name: '전북은행', displayName: '전북은행', iconPosition: '-310px -110px'},
  {name: '제주은행', displayName: '제주은행', iconPosition: '-310px -210px'},
  {name: 'IBK기업은행', displayName: '기업은행', iconPosition: '-10px -310px'},
  {name: 'KDB산업은행', displayName: '산업은행', iconPosition: '-110px -310px'},
  {name: '수협은행', displayName: '수협은행', iconPosition: '-210px -310px'},
  {name: 'NH농협', displayName: '농협은행', iconPosition: '-310px -310px'},
  {name: '새마을금고', displayName: '새마을금고', iconPosition: '-410px -10px'},
  {name: '우체국은행', displayName: '우체국은행', iconPosition: '-410px -110px'},
  {name: '신협은행', displayName: '신협은행', iconPosition: '-410px -210px'},
  {name: 'SBI저축', displayName: 'SBI저축', iconPosition: '-410px -310px'},
  {name: '카카오뱅크', displayName: '카카오뱅크', iconPosition: '-10px -410px'},
  {name: '토스뱅크', displayName: '토스뱅크', iconPosition: '-110px -410px'},
  {name: '케이뱅크', displayName: '케이뱅크', iconPosition: '-210px -410px'},
] as const;

export default BANKS;
