name: design-push

on:
  pull_request:
    types: [opened, synchronize]
    branches: [main, develop]
    paths:
      - 'HDesign/**'

jobs:
  build:
    runs-on: ubuntu-latest  

    defaults:
      run:
        shell: bash
        working-directory: ./HDesign

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Node.js
      uses: actions/setup-node@v2 
      with:
        node-version: '20.15.1'

    - name: Install dependencies
      working-directory: ./HDesign
      run: npm install  

    - name: Run lint
      working-directory: ./HDesign
      run: npm run lint

    - name: Storybook build
      working-directory: ./HDesign
      run: npm run build-storybook

    - name: Chromatic
      working-directory: ./HDesign
      run: npx chromatic --project-token=${{ secrets.CHROMATIC_TOKEN }}
      