name: frontend-merge

on:
  push:
    branches:
      - '**'
    paths:
      - 'client/**'

jobs:
  test:
    runs-on: ubuntu-latest  
    
    defaults:
      run:
        shell: bash
        working-directory: ./client

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Node.js
      uses: actions/setup-node@v2 
      with:
        node-version: '20.15.1'

    - name: Install dependencies
      working-directory: ./client
      run: npm install  

    - name: Run linter
      working-directory: ./client
      run: npm run lint  

  deploy:
    runs-on: ubuntu-latest  
    
    defaults:
      run:
        shell: bash
        working-directory: ./client

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 

    - name: Set up Node.js
      uses: actions/setup-node@v2 
      with:
        node-version: '20'  

    - name: Install dependencies
      run: npm install  

    - name: Build project
      run: npm run build  

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-2'
        S3_BUCKET: 'techcourse-project-2024'
      run: |
        aws s3 sync ./build s3://$S3_BUCKET/main